<?php

return [
    'enabled' => env('AI_HELPER_ENABLED', false),
    'model' => env('OPENAI_HELPER_MODEL', 'gpt-5.4-mini'),
    'api_key' => env('OPENAI_API_KEY'),
    'base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
    'timeout' => (int) env('AI_HELPER_TIMEOUT_SECONDS', 60),
    'max_message_length' => (int) env('AI_HELPER_MAX_MESSAGE_LENGTH', 2000),
    'knowledge_upload_max_kb' => (int) env('AI_HELPER_KNOWLEDGE_UPLOAD_MAX_KB', 10240),
    'markdown_upload_max_kb' => (int) env('AI_HELPER_MARKDOWN_UPLOAD_MAX_KB', 1024),
    'knowledge_upload_rate_limit_per_minute' => (int) env('AI_HELPER_KNOWLEDGE_UPLOAD_RATE_LIMIT_PER_MINUTE', 6),
    'knowledge_upload_ip_rate_limit_per_minute' => (int) env('AI_HELPER_KNOWLEDGE_UPLOAD_IP_RATE_LIMIT_PER_MINUTE', 30),
    // Positive limits fail the document instead of partially indexing it; zero disables the limit.
    'knowledge_extract_max_characters' => (int) env('AI_HELPER_KNOWLEDGE_EXTRACT_MAX_CHARACTERS', 2000000),
    'knowledge_chunk_characters' => (int) env('AI_HELPER_KNOWLEDGE_CHUNK_CHARACTERS', 1000),
    // Zero disables the chunk-count limit.
    'knowledge_max_chunks_per_entry' => (int) env('AI_HELPER_KNOWLEDGE_MAX_CHUNKS_PER_ENTRY', 2500),
    'knowledge_retrieval_limit' => (int) env('AI_HELPER_KNOWLEDGE_RETRIEVAL_LIMIT', 6),
    'knowledge_catalogue_limit' => (int) env('AI_HELPER_KNOWLEDGE_CATALOGUE_LIMIT', 250),
    'knowledge_strict_readiness' => env('AI_HELPER_KNOWLEDGE_STRICT_READINESS', true),
    'knowledge_require_async_queue' => env('AI_HELPER_KNOWLEDGE_REQUIRE_ASYNC_QUEUE', true),
    'knowledge_ocr_enabled' => env('AI_HELPER_KNOWLEDGE_OCR_ENABLED', true),
    'knowledge_ocr_min_native_words' => (int) env('AI_HELPER_KNOWLEDGE_OCR_MIN_NATIVE_WORDS', 12),
    'knowledge_ocr_min_native_characters' => (int) env('AI_HELPER_KNOWLEDGE_OCR_MIN_NATIVE_CHARACTERS', 100),
    'knowledge_max_pdf_pages' => (int) env('AI_HELPER_KNOWLEDGE_MAX_PDF_PAGES', 250),
    'knowledge_max_ocr_pages_per_document' => (int) env('AI_HELPER_KNOWLEDGE_MAX_OCR_PAGES_PER_DOCUMENT', 20),
    'knowledge_ocr_document_timeout_seconds' => (int) env('AI_HELPER_KNOWLEDGE_OCR_DOCUMENT_TIMEOUT_SECONDS', 600),
    'knowledge_job_timeout_seconds' => (int) env('AI_HELPER_KNOWLEDGE_JOB_TIMEOUT_SECONDS', 900),
    'knowledge_visual_content_minimum_ratio' => (float) env('AI_HELPER_KNOWLEDGE_VISUAL_CONTENT_MINIMUM_RATIO', 0.0005),
    'knowledge_visual_review_minimum_ratio' => (float) env('AI_HELPER_KNOWLEDGE_VISUAL_REVIEW_MINIMUM_RATIO', 0.05),
    'knowledge_visual_review_maximum_ocr_words' => (int) env('AI_HELPER_KNOWLEDGE_VISUAL_REVIEW_MAXIMUM_OCR_WORDS', 120),
    'knowledge_ocr_temporary_retention_hours' => (int) env('AI_HELPER_KNOWLEDGE_OCR_TEMPORARY_RETENTION_HOURS', 24),
    'knowledge_ocr_languages' => env('AI_HELPER_KNOWLEDGE_OCR_LANGUAGES', 'eng+msa'),
    'knowledge_ocr_dpi' => (int) env('AI_HELPER_KNOWLEDGE_OCR_DPI', 300),
    'knowledge_ocr_timeout_seconds' => (int) env('AI_HELPER_KNOWLEDGE_OCR_TIMEOUT_SECONDS', 120),
    'knowledge_pdftotext_binary' => env('AI_HELPER_PDFTOTEXT_BINARY', 'pdftotext'),
    'knowledge_pdfinfo_binary' => env('AI_HELPER_PDFINFO_BINARY', 'pdfinfo'),
    'knowledge_pdftoppm_binary' => env('AI_HELPER_PDFTOPPM_BINARY', 'pdftoppm'),
    'knowledge_tesseract_binary' => env('AI_HELPER_TESSERACT_BINARY', 'tesseract'),
    'knowledge_require_shared_review' => env('AI_HELPER_KNOWLEDGE_REQUIRE_SHARED_REVIEW', true),
    'knowledge_max_active_uploads_per_user' => (int) env('AI_HELPER_KNOWLEDGE_MAX_ACTIVE_UPLOADS_PER_USER', 100),
    'knowledge_max_upload_bytes_per_user' => (int) env('AI_HELPER_KNOWLEDGE_MAX_UPLOAD_BYTES_PER_USER', 2147483648),
    'knowledge_max_total_upload_bytes' => (int) env('AI_HELPER_KNOWLEDGE_MAX_TOTAL_UPLOAD_BYTES', 21474836480),
    'knowledge_deleted_retention_days' => (int) env('AI_HELPER_KNOWLEDGE_DELETED_RETENTION_DAYS', 30),
    'knowledge_failed_retention_days' => (int) env('AI_HELPER_KNOWLEDGE_FAILED_RETENTION_DAYS', 14),
    'history_turns' => (int) env('AI_HELPER_HISTORY_TURNS', 12),
    'history_max_characters' => (int) env('AI_HELPER_HISTORY_MAX_CHARACTERS', 12000),
    'rate_limit_per_minute' => (int) env('AI_HELPER_RATE_LIMIT_PER_MINUTE', 12),
];
