<?php

return [
    'version' => 1,

    /*
    |--------------------------------------------------------------------------
    | Deterministic answer-quality cases
    |--------------------------------------------------------------------------
    |
    | Every registered workflow must be represented. Assertions are semantic
    | tokens and routing contracts rather than brittle whole-answer snapshots.
    |
    */
    'cases' => [
        [
            'id' => 'inspection.fire-truck.ms',
            'message' => 'cara jalankan pemeriksaan harian lori bomba',
            'language' => 'bm',
            'expected_task' => 'inspection.conduct',
            'expected_workflow' => 'inspection.conduct.fire_truck',
            'expected_guide' => 'inspection-fire-truck-conduct',
            'required' => ['Inspection', 'Fire Truck Daily Readiness', 'Submit Report'],
            'forbidden' => ['Fire Extinguisher'],
        ],
        [
            'id' => 'inspection.hse.en',
            'message' => 'how do I conduct an HSE inspection',
            'language' => 'en',
            'expected_task' => 'inspection.conduct',
            'expected_workflow' => 'inspection.conduct.hse',
            'expected_guide' => 'inspection-manage',
            'required' => ['Health Safety Environment', 'Observation', 'Evidence'],
            'forbidden' => ['Fire Truck'],
        ],
        [
            'id' => 'inspection.extinguisher.en',
            'message' => 'how do I conduct a fire extinguisher inspection',
            'language' => 'en',
            'expected_task' => 'inspection.conduct',
            'expected_workflow' => 'inspection.conduct.fire_extinguisher',
            'expected_guide' => 'inspection-fire-extinguisher-conduct',
            'required' => ['Fire Extinguisher', 'By Area', 'Serial Number'],
            'forbidden' => ['Fire Truck Daily Readiness'],
        ],
        [
            'id' => 'inspection.general.en',
            'message' => 'how can I submit a general inspection',
            'language' => 'en',
            'expected_task' => 'inspection.conduct',
            'expected_workflow' => 'inspection.conduct',
            'expected_guide' => 'inspection-manage',
            'required' => ['Inspection Type', 'Checklist', 'Submit Report'],
        ],
        [
            'id' => 'inspection.settings.en',
            'message' => 'how do I configure inspection workflow settings',
            'language' => 'en',
            'expected_task' => 'inspection.workflow.configure',
            'expected_workflow' => 'inspection.workflow.configure',
            'expected_guide' => 'inspection-workflow-settings',
            'required' => ['Reporting Settings', 'Fallback Review', 'Self-review'],
            'forbidden' => ['Conduct Inspection'],
        ],
        [
            'id' => 'leave.apply.ms',
            'message' => 'macam mana nak mohon cuti',
            'language' => 'bm',
            'expected_task' => 'leave.self_service',
            'expected_workflow' => 'leave.self_service',
            'expected_guide' => 'leave-self-service',
            'required' => ['Leave', 'Leave Type', 'Save Draft', 'Submit'],
        ],
        [
            'id' => 'overtime.apply.en',
            'message' => 'how do I apply for overtime',
            'language' => 'en',
            'expected_task' => 'overtime.self_service',
            'expected_workflow' => 'overtime.self_service',
            'expected_guide' => 'overtime-self-service',
            'required' => ['Overtime', 'Application Type', 'Submit request'],
        ],
        [
            'id' => 'payroll.payslip.ms',
            'message' => 'cara lihat dan muat turun slip gaji',
            'language' => 'bm',
            'expected_task' => 'payroll.payslip.view',
            'expected_workflow' => 'payroll.payslip.view',
            'expected_guide' => 'payroll-self-service',
            'required' => ['Payroll', 'Payslips', 'Download payslip'],
        ],
        [
            'id' => 'payroll.claim.en',
            'message' => 'how do I create and submit a salary claim',
            'language' => 'en',
            'expected_task' => 'payroll.claim.submit',
            'expected_workflow' => 'payroll.claim.submit',
            'expected_guide' => 'payroll-claims',
            'required' => ['Claims', 'Claim Type', 'Submit claim'],
            'forbidden' => ['Mark paid'],
        ],
        [
            'id' => 'roster.manage.en',
            'message' => 'how do I create and publish a duty roster',
            'language' => 'en',
            'expected_task' => 'roster.manage',
            'expected_workflow' => 'roster.manage',
            'expected_guide' => 'roster-manage',
            'required' => ['Roster', 'Save draft', 'Publish'],
        ],
        [
            'id' => 'teams.manage.ms',
            'message' => 'cara tambah pekerja ke dalam pasukan',
            'language' => 'bm',
            'expected_task' => 'teams.manage',
            'expected_workflow' => 'teams.manage',
            'expected_guide' => 'teams-manage',
            'required' => ['Teams', 'Add Team', 'Members'],
        ],
        [
            'id' => 'reports.navigate.en',
            'message' => 'how do I create a report',
            'language' => 'en',
            'expected_task' => 'reports.navigate',
            'expected_workflow' => 'reports.navigate',
            'expected_guide' => 'reports-navigation',
            'required' => ['Reports', 'Report Type', 'New Report'],
        ],
        [
            'id' => 'reports.erco.create.ms',
            'message' => 'macam mana nak tulis report erco',
            'language' => 'bm',
            'expected_task' => 'reports.erco.manage',
            'expected_workflow' => 'reports.erco.manage',
            'expected_guide' => 'erco-reports',
            'required' => ['Reports', 'ERCO', 'New ERCO Report', 'Save Draft', 'Submit'],
            'forbidden' => ['Drill', 'Fitness Test'],
        ],
        [
            'id' => 'reports.erco.submitted-edit.en',
            'message' => 'how can I revise an ERCO report',
            'language' => 'en',
            'expected_task' => 'reports.erco.manage',
            'expected_workflow' => 'reports.erco.manage',
            'expected_guide' => 'erco-reports',
            'ui_state' => [
                'record_status' => 'submitted',
                'available_actions' => ['review', 'reject'],
            ],
            'required' => ['Existing Record', 'Submitted', 'edit', 'not available'],
            'forbidden' => ['ERCO Form', 'Save Draft', 'Select **Submit**'],
        ],
        [
            'id' => 'reports.drill.edit.ms',
            'message' => 'cara kemas kini laporan latihan',
            'language' => 'bm',
            'expected_task' => 'reports.drill.manage',
            'expected_workflow' => 'reports.drill.manage',
            'expected_guide' => 'drill-reports',
            'required' => ['Drill', 'Existing Draft', 'Save Draft'],
            'forbidden' => ['New ERCO Report'],
        ],
        [
            'id' => 'reports.fitness.submit.en',
            'message' => 'how do I submit a fitness report',
            'language' => 'en',
            'expected_task' => 'reports.fitness.manage',
            'expected_workflow' => 'reports.fitness.manage',
            'expected_guide' => 'fitness-reports',
            'required' => ['Fitness Test', 'Existing Draft', 'Submit'],
            'forbidden' => ['Download'],
        ],
        [
            'id' => 'reports.review.en',
            'message' => 'how do I review and approve a submitted report',
            'language' => 'en',
            'expected_task' => 'reports.review',
            'expected_workflow' => 'reports.review',
            'expected_guide' => 'report-management',
            'required' => ['Report Review', 'Review', 'Approve', 'Reject'],
        ],
        [
            'id' => 'payroll.payment.en',
            'message' => 'how do I mark an approved salary claim as paid',
            'language' => 'en',
            'expected_task' => 'payroll.payment.manage',
            'expected_workflow' => 'payroll.payment.manage',
            'expected_guide' => 'payment-actions',
            'required' => ['Payroll Records', 'Approved Claim', 'Mark paid', 'Paid State'],
            'forbidden' => ['Submit claim'],
        ],
        [
            'id' => 'users.manage.en',
            'message' => 'how do I create and activate a user account',
            'language' => 'en',
            'expected_task' => 'users.manage',
            'expected_workflow' => 'users.manage',
            'expected_guide' => 'user-administration',
            'required' => ['User Management', 'Create user', 'Activate'],
        ],
        [
            'id' => 'roles.permissions.ms',
            'message' => 'cara ubah dan simpan kebenaran akses peranan',
            'language' => 'bm',
            'expected_task' => 'roles.permissions.manage',
            'expected_workflow' => 'roles.permissions.manage',
            'expected_guide' => 'role-permissions',
            'required' => ['Role Permissions', 'Permission Matrix', 'Save'],
        ],
        [
            'id' => 'settings.module-activation.en',
            'message' => 'how do I enable a module',
            'language' => 'en',
            'expected_task' => 'settings.module_activation',
            'expected_workflow' => 'settings.module_activation',
            'expected_guide' => 'module-activation',
            'required' => ['Module Activation', 'Dependencies', 'Save'],
        ],

        // Clarification cases intentionally have no deterministic workflow.
        [
            'id' => 'clarify.report-type.en',
            'message' => 'how do I submit a report',
            'language' => 'en',
            'expected_clarification' => 'missing_report_type',
            'expected_options' => ['erco', 'drill', 'fitness', 'inspection'],
        ],
        [
            'id' => 'clarify.report-action.ms',
            'message' => 'cara semak report ERCO',
            'language' => 'bm',
            'expected_clarification' => 'ambiguous_action',
            'expected_options' => ['view', 'review'],
        ],
        [
            'id' => 'clarify.record-context.en',
            'message' => 'how do I approve this',
            'language' => 'en',
            'expected_clarification' => 'missing_record_context',
        ],
        [
            'id' => 'clarify.unsupported.en',
            'message' => 'how do I delete an approved ERCO report',
            'language' => 'en',
            'expected_clarification' => 'unsupported_action',
        ],
        [
            'id' => 'clarify.compound.en',
            'message' => 'how do I inspect and physically maintain a fire extinguisher',
            'language' => 'en',
            'expected_clarification' => 'compound_request',
            'expected_options' => ['inspection_workflow', 'physical_maintenance'],
        ],
    ],
];
