<?php

return [
    'enabled' => env('AI_HELPER_ENABLED', false),
    'model' => env('OPENAI_HELPER_MODEL', 'gpt-5.4-mini'),
    'api_key' => env('OPENAI_API_KEY'),
    'base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
    'timeout' => (int) env('AI_HELPER_TIMEOUT_SECONDS', 60),
    'max_message_length' => (int) env('AI_HELPER_MAX_MESSAGE_LENGTH', 2000),
    'document_upload_max_kb' => (int) env('AI_HELPER_DOCUMENT_UPLOAD_MAX_KB', 10240),
    'document_max_active_uploads_per_user' => (int) env('AI_HELPER_DOCUMENT_MAX_ACTIVE_UPLOADS_PER_USER', 100),
    'document_max_upload_bytes_per_user' => (int) env('AI_HELPER_DOCUMENT_MAX_UPLOAD_BYTES_PER_USER', 2147483648),
    'document_max_total_upload_bytes' => (int) env('AI_HELPER_DOCUMENT_MAX_TOTAL_UPLOAD_BYTES', 21474836480),
    'reference_corpus_path' => env('AI_HELPER_REFERENCE_CORPUS_PATH', ''),
    'markdown_upload_max_kb' => (int) env('AI_HELPER_MARKDOWN_UPLOAD_MAX_KB', 1024),
    'knowledge_upload_rate_limit_per_minute' => (int) env('AI_HELPER_KNOWLEDGE_UPLOAD_RATE_LIMIT_PER_MINUTE', 6),
    'knowledge_upload_ip_rate_limit_per_minute' => (int) env('AI_HELPER_KNOWLEDGE_UPLOAD_IP_RATE_LIMIT_PER_MINUTE', 30),
    'knowledge_chunk_characters' => (int) env('AI_HELPER_KNOWLEDGE_CHUNK_CHARACTERS', 1500),
    // Zero disables the chunk-count limit.
    'knowledge_max_chunks_per_entry' => (int) env('AI_HELPER_KNOWLEDGE_MAX_CHUNKS_PER_ENTRY', 2500),
    'retrieval_v2' => env('AI_HELPER_RETRIEVAL_V2', true),
    'retrieval_v3' => env('AI_HELPER_RETRIEVAL_V3', false),
    'system_guides_enabled' => env('AI_HELPER_SYSTEM_GUIDES_ENABLED', false),
    'system_guide_final_corpus_enforced' => env('AI_HELPER_SYSTEM_GUIDE_FINAL_CORPUS_ENFORCED', true),
    'knowledge_retrieval_limit' => (int) env('AI_HELPER_KNOWLEDGE_RETRIEVAL_LIMIT', 18),
    'knowledge_document_candidate_limit' => (int) env('AI_HELPER_KNOWLEDGE_DOCUMENT_CANDIDATE_LIMIT', 12),
    'retrieval_candidate_chunks' => (int) env('AI_HELPER_RETRIEVAL_CANDIDATE_CHUNKS', 40),
    'retrieval_min_lexical_coverage' => (float) env('AI_HELPER_RETRIEVAL_MIN_LEXICAL_COVERAGE', 0.6),
    'retrieval_min_semantic_similarity' => (float) env('AI_HELPER_RETRIEVAL_MIN_SEMANTIC_SIMILARITY', 0.42),
    'knowledge_max_chunks_per_document' => (int) env('AI_HELPER_KNOWLEDGE_MAX_CHUNKS_PER_DOCUMENT', 4),
    'knowledge_exact_document_chunk_limit' => (int) env('AI_HELPER_KNOWLEDGE_EXACT_DOCUMENT_CHUNK_LIMIT', 12),
    'knowledge_adjacent_chunk_window' => (int) env('AI_HELPER_KNOWLEDGE_ADJACENT_CHUNK_WINDOW', 1),
    'knowledge_context_token_budget' => (int) env('AI_HELPER_KNOWLEDGE_CONTEXT_TOKEN_BUDGET', 12000),
    'knowledge_citation_limit' => (int) env('AI_HELPER_KNOWLEDGE_CITATION_LIMIT', 12),
    'citation_validation_enabled' => env('AI_HELPER_CITATION_VALIDATION_ENABLED', true),
    'critical_fact_validation_enabled' => env('AI_HELPER_CRITICAL_FACT_VALIDATION_ENABLED', true),
    'rerank_enabled' => env('AI_HELPER_RERANK_ENABLED', false),
    'rerank_model' => env('OPENAI_HELPER_RERANK_MODEL', env('OPENAI_HELPER_MODEL', 'gpt-5.4-mini')),
    'rerank_candidate_limit' => (int) env('AI_HELPER_RERANK_CANDIDATE_LIMIT', 32),
    'rerank_min_relevance' => (int) env('AI_HELPER_RERANK_MIN_RELEVANCE', 1),
    'rerank_timeout' => (int) env('AI_HELPER_RERANK_TIMEOUT_SECONDS', 20),
    'grounding_verification_mode' => env('AI_HELPER_GROUNDING_VERIFICATION_MODE', 'disabled'),
    'verifier_model' => env('OPENAI_HELPER_VERIFIER_MODEL', env('OPENAI_HELPER_MODEL', 'gpt-5.4-mini')),
    'verifier_timeout' => (int) env('AI_HELPER_VERIFIER_TIMEOUT_SECONDS', 25),
    'verification_max_attempts' => (int) env('AI_HELPER_VERIFICATION_MAX_ATTEMPTS', 2),
    'embedding_enabled' => env('AI_HELPER_EMBEDDING_ENABLED', true),
    'embedding_model' => env('AI_HELPER_EMBEDDING_MODEL', 'text-embedding-3-small'),
    'embedding_dimensions' => (int) env('AI_HELPER_EMBEDDING_DIMENSIONS', 512),
    'embedding_batch_size' => (int) env('AI_HELPER_EMBEDDING_BATCH_SIZE', 32),
    // Conservative estimates keep requests below the provider's aggregate token limit.
    'embedding_batch_token_budget' => (int) env('AI_HELPER_EMBEDDING_BATCH_TOKEN_BUDGET', 100000),
    'embedding_max_input_characters' => (int) env('AI_HELPER_EMBEDDING_MAX_INPUT_CHARACTERS', 6000),
    'embedding_timeout' => (int) env('AI_HELPER_EMBEDDING_TIMEOUT_SECONDS', 30),
    'knowledge_catalogue_limit' => (int) env('AI_HELPER_KNOWLEDGE_CATALOGUE_LIMIT', 250),
    'knowledge_strict_readiness' => env('AI_HELPER_KNOWLEDGE_STRICT_READINESS', true),
    'knowledge_job_timeout_seconds' => (int) env('AI_HELPER_KNOWLEDGE_JOB_TIMEOUT_SECONDS', 900),
    'knowledge_max_active_uploads_per_user' => (int) env('AI_HELPER_KNOWLEDGE_MAX_ACTIVE_UPLOADS_PER_USER', 100),
    'knowledge_max_upload_bytes_per_user' => (int) env('AI_HELPER_KNOWLEDGE_MAX_UPLOAD_BYTES_PER_USER', 2147483648),
    'knowledge_max_total_upload_bytes' => (int) env('AI_HELPER_KNOWLEDGE_MAX_TOTAL_UPLOAD_BYTES', 21474836480),
    'knowledge_deleted_retention_days' => (int) env('AI_HELPER_KNOWLEDGE_DELETED_RETENTION_DAYS', 30),
    'knowledge_failed_retention_days' => (int) env('AI_HELPER_KNOWLEDGE_FAILED_RETENTION_DAYS', 14),
    'history_turns' => (int) env('AI_HELPER_HISTORY_TURNS', 12),
    'history_max_characters' => (int) env('AI_HELPER_HISTORY_MAX_CHARACTERS', 12000),
    'rate_limit_per_minute' => (int) env('AI_HELPER_RATE_LIMIT_PER_MINUTE', 12),
];
